import type { Metadata } from "next";
import "../globals.css";
import Footer from "../components/Footer";
import { CartProvider } from "@/app/cartContext";
import { ClerkProvider, SignedOut } from "@clerk/nextjs";
import {ToastContextProvider} from "@/app/toastContext";
import Navbar from "../components/Navbar";
import Topbar from "../components/Top-black";

export const metadata: Metadata = {
  title: "Bandage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <CartProvider>
          <body>
            <SignedOut></SignedOut>
            <ToastContextProvider>
            <Topbar  className="black1"/>
              <Navbar/>
            {children}
            </ToastContextProvider>
            
            <Footer />
          </body>
        </CartProvider>
      </html>
    </ClerkProvider>
  );
}
